version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "5000:5000"
    networks:
      - app-network

  apache:
    build: ./apache
    container_name: apache_proxy
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge